name: CD — Build & Release
on:
  push:
    tags: ['v*']   # приклад: v1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read manifest version
        id: ver
        run: echo "ver=$(jq -r '.version' extension/manifest.json)" >> $GITHUB_OUTPUT

      - name: Check tag matches manifest.json
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          MANIFEST_VER=$(jq -r '.version' extension/manifest.json)
          [ "$TAG" = "$MANIFEST_VER" ] || (echo "Tag v$TAG != $MANIFEST_VER" && exit 1)

      - name: Pack extension
        run: |
          cd extension
          zip -r ../link-highlighter-${{ steps.ver.outputs.ver }}.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: link-highlighter-${{ steps.ver.outputs.ver }}.zip
          generate_release_notes: true
