name: CD — Test, Build & Release

on:
  push:
    tags: ['v*']              # приклад: v1.2.8
  workflow_dispatch: {}        # опційно: ручний запуск

permissions:
  contents: write              # потрібно для створення GitHub Release

jobs:
  test:
    name: Run Playwright tests (container)
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.47.0-jammy   # ← виправлено
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # У контейнері вже є Node/Chromium; залишимо як страховку
      - name: Install deps
        run: npm ci || npm i

      - name: Ensure Playwright deps
        run: npx playwright install --with-deps chromium

      - name: Run tests (headed via Xvfb)
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' \
          npx playwright test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  build-and-release:
    name: Build ZIP & create GitHub Release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq + zip
        run: sudo apt-get update && sudo apt-get install -y jq zip

      - name: Read manifest version
        id: ver
        run: echo "ver=$(jq -r '.version' extension/manifest.json)" >> $GITHUB_OUTPUT

      - name: Check tag matches manifest.json
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          MANIFEST_VER=$(jq -r '.version' extension/manifest.json)
          if [ "$TAG" != "$MANIFEST_VER" ]; then
            echo "Tag v$TAG != manifest.json version $MANIFEST_VER"
            exit 1
          fi

      - name: Pack extension
        run: |
          cd extension
          zip -r ../link-highlighter-${{ steps.ver.outputs.ver }}.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: link-highlighter-${{ steps.ver.outputs.ver }}.zip
          generate_release_notes: true
